### ISSUE TITLE
Multiple assignments cause an error in the editor

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/WebEditor#43]
Currently, there is an error message in assignments like these, although they are legal:
```
forward data
set Encryption.Encrypted = TRUE
set Sensitivity.Personal = FALSE
```

Hopefully, this is only a regex problem (which would be easy to fix) and not a model problem (which would be hard to fix).

Update: The json file seems to be correct, so probably a display problem only.
```
"behavior": "forward data\r\nset Encryption.Encrypted = TRUE\r\nset Sensitivity.Personal = FALSE",
```

**Comment by sebinside** [comment]
@Nicolas-Boltz (employee of the month) already found the problem: https://github.com/DataFlowAnalysis/WebEditor/blob/703f5bbe5b8b80ef5ad72b1b21fc8acb21bd7bff/src/features/dfdElements/outputPortBehaviorValidation.ts#L43

**Comment by hlxid** [comment]
Was the diagram generated through some other tool or created in the editor?
`\r\n` should not happen in web contexts and when testing this on linux and windows with the editor none produce `\r\n`, only `\n` as expected.

**Comment by Nicolas-Boltz** [comment]
Nice to see you are still following what is going on in the repository :).
This even occurs when opening the default model in the [editor](https://dataflowanalysis.github.io/WebEditor/) and simply adding a 'set' statement to an existing behavior, like, for example, the output pin of 'display'. 
@sebinside and I both get this error.

**Comment by hlxid** [comment]
Was now able to reproduce this and will implement the proposed fix through setting End-of-Line in monaco to only be `\n`
