### ISSUE TITLE
Empty Flow Names cause inconsistencies

### ISSUE THREAD

**Issue by 01Parzival10** [DataFlowAnalysis/WebEditor#51]
For preserving control flows (for example for converting PCM 2 DFD) we generally use Flows with empty names.
When converting these Assignments to the WebEditor representation the empty flow names cause issues, since  the WebEditor works name and not ID based.
This means when going from PCM -> DFD -> JSON we create invalid assignments in the WebEditor and cannot convert back into DFD without fixing it.

Possible Solutions:
1. Dont add empty flow names - use something like "control" (Would cause issues if there is already a DFV called control present)
2. Create Logic in the WebEditor for handling one empty flow per node by addressing it with (empty / control ....) (This would cause issues if 2 empty flows are present, however we forbid 2 flows with the same name anyway)

**Comment by sebinside** [comment]
~
